use_frameworks!

platform :ios, '9.0'

target 'SwiftTLV_Example' do
  pod 'SwiftTLV', :path => '../'

  target 'SwiftTLV_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 2.2.0'
    #pod 'Nimble', '~> 8.0.7'
     pod 'Quick'
     pod 'Nimble'
  end
end
